<?php
/** @var Adverti_Calculate_Block_ProductAttributes $this */
?>

<div id="attributes" class="specifications vsmall-size lh-sm js-text-desc">
    <?php foreach ($this->getProductParameters() as $key => $attribute): ?>
        <div class="specifications__item">
            <?php if ($attribute['type'] == "multiselect"): ?>
                <label class="gray">
                    <?php echo $attribute['label'] ?>:
                    <div class="d-select d-select_w-a d-select_min-w-260 print-inline-block js-d-select">
                        <select name="haracteristik_variants[]" class="d-select__inner">
                            <?php foreach (explode(',', $attribute['value']) as $productMultiAttribute): ?>
                                <?php $value = $attribute['label'] . ': ' . trim($productMultiAttribute); ?>
                                <option value="<?php echo $value; ?>" <?php
                                if (in_array($value, $this->getMultiAttributes())):?>selected<?php endif;?>>
                                    <?php echo $productMultiAttribute ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </label>
            <?php else: ?>
                <span class="gray"><?php echo $attribute['label'] ?>:</span>
                <?php echo $attribute['value'] ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>

    <!-- TODO кастомные аттрибуты -->
    <div class="specifications__item">
        Артикул поставляется кратностью 30 шт.
    </div>
    <div class="specifications__item available">
        <span class="min-size">Доступно для заказа: <strong>5531 шт.</strong></span>
        <div class="select-help-group__help">
            <div class="button-helper js-button-helper-with-scroll js-button-helper-with-scroll-infliction print-hide">
                <a href="javascript:void(0);" class="button-helper__button"><span class="button-helper__button__inner"></span></a>
                <div class="button-helper__text button-helper__text_for-scroll vsmall-size lh-sm">
                    <div class="button-helper__text__inner">
                        Текст подсказки
                    </div>
                </div>
            </div>
        </div>
        <span class="tip-more">Нужно больше</span>
    </div>
    <div class="specifications__item">
        <span class="gray">Дополнительно в резерве:</span> 0 шт.
    </div>

</div>