<?php
/**
 * naumov
 */
?>

<div class="entry-edit">
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Калькулятор</h4>
    <!--<div class="form-buttons"><button id="create_attribute_8" title="Создать новый атрибут" type="button" class="scalable add" onclick="create_attribute_8JsObject.create();" style=""><span><span><span>Создать новый атрибут</span></span></span></button><script type="text/javascript">//<![CDATA[
            var create_attribute_8JsObject = new Product.Attributes('create_attribute_8');
            create_attribute_8JsObject.setConfig({"tab_id":"group_8","group_id":"8","store_id":0,"attribute_set_id":"4","type_id":"simple","product_id":"10223","url":"http:\/\/www.advertimg.naumov\/index.php\/admin\/catalog_product_attribute\/new\/group\/8\/tab\/group_8\/store\/0\/product\/10223\/set\/4\/type\/simple\/popup\/1\/key\/bb5904eeb5b43cd6e6ec2905282d836a\/"});

            //]]></script></div>-->
</div>
<div class="fieldset fieldset-wide" id="group_fields8">
<div class="hor-scroll">
<table cellspacing="0" class="form-list">
<tbody>
<tr>
    <td class="label"><label for="price">Цена поставщика <span class="required">*</span></label></td>
    <td class="value">
        <input id="price" name="price_post" value="0.00" class=" required-entry validate-zero-or-greater input-text required-entry" type="text">
        <strong>[RUB]</strong</td>
    <td class="scope-label"><span class="nobr"></span></td>
</tr>
<tr>
    <td class="label"><label for="price">Метод расщёта <span class="required">*</span></label></td>
    <td class="value">
        <input id="price" name="method_calculate" value="kk" class=" required-entry input-text required-entry" type="text">
        <strong>[KK или IP]</strong</td>
    <td class="scope-label"><span class="nobr"></span></td>
</tr>
<tr>
    <td class="label"><label for="price">Минимальный тираж <span class="required">*</span></label></td>
    <td class="value">
        <input id="price" name="amount" value="100" class=" required-entry input-text required-entry" type="text">
        <strong>[ШТ]</strong</td>
    <td class="scope-label"><span class="nobr"></span></td>
</tr>

</tbody>
</table>
</div>
</div>
</div>
