<?php
/** @var Mage_Catalog_Block_Product_List $this */
$_productCollection = $this->getLoadedProductCollection();
$_productCollection->clear(); //TODO wtf? иначе не работает пагинация
$_helper = $this->helper('catalog/output');
?>
<?php //echo $this->getToolbarHtml() ?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php //echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if ($this->getMode() != 'grid'): /*?>
        <?php $_iterator = 0; ?>
        <ol class="products-list" id="products-list">
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
                    <?php // Product Image ?>
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                       class="product-image"><img
                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>"
                            width="135" height="135"
                            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
                    <?php // Product description ?>
                    <div class="product-shop">
                        <div class="f-fix">
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                        title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                            </h2>
                            <?php if ($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                            <?php endif; ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                            <?php if ($_product->isSaleable()): ?>
                                <p>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                            class="button btn-cart"
                                            onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                        <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                </p>
                            <?php else: ?>
                                <p class="availability out-of-stock">
                                    <span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <div class="desc std">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                   title="<?php echo $_productNameStripped ?>"
                                   class="link-learn"><?php echo $this->__('Learn More') ?></a>
                            </div>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                           class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"
                                                                            class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                                    </li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php */
    else: ?>

        <?php // Grid Mode ?>

        <div class="product-w">
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                //var_dump($_product->getMainCategory());
                ///var_dump('st');
                /*$category = $_product->getData('main_category');
                $category = $_product->getCategory($category);
                $url = $category->getData('url_path');
                $tmp = explode('.',$url);
                $url = '/'.$tmp[0].'/'.$_product->getData('url_key').'.html';*/
                $url = $_product->getProductUrl();

                //var_dump($url);
                ?>
                <a href="<?php echo $url ?>" class="product">
                    <div class="product__title_wrapper">
                        <div class="product__title"><?php echo $this->escapeHtml($_product->getName()) ?></div>
                        <div class="product__short"><?php
                            echo $this->stripTags($_product->getShortDescription(),
                                '<p><strong><span><br>') ?>
                        </div>
                    </div>
                    <div class="product__image-w">
                        <img src="<?php
                        echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210)->setQuality(100); ?>" alt="<?php
                        echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                    </div>
                    <div class="product__price">
                        <?php if ($_product->getData('recommended_count') !== null && $_product->getData('recommended_price') !== null) : ?>
                            <span class="produuct__price_price">
                    <?php echo number_format($_product->getData('recommended_price'), 2, ',', ' ');?>
                                &nbsp;руб.
                            </span> <span class="product__price_unit">/шт.</span><br/>
                            *при тираже&nbsp;<?php echo number_format($_product->getData('recommended_count'), 0, ',', ' ') ?>&nbsp;шт.
                        <?php else : ?>
                            <span class="produuct__price_price">
                            <?php if ($_product->getData('price_min')): ?>
                                <?php echo $_product->getData('price_min') ?>
                            <?php endif ?>
                                <?php if ($_product->getData('price_max')) : ?>
                                    — <?php echo $_product->getData('price_max') ?>
                                <?php endif ?> &nbsp;руб.
                            </span>
                        <?php endif ?>
                    </div>
                </a>
            <?php endforeach ?>
        </div>
        <?php /*?>
        <script
            type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <?php */
        ?>
    <?php endif; ?>

    <?php ?>
    <div class="toolbar-bottom">
    <?php echo $this->getToolbarHtml() ?>
    </div><?php
    ?>
<?php endif; ?>
