<?php
//die('tset');
/** @var Adverti_Adverti_Block_ChildCategoriesProducts $this */
/** @var Mage_Catalog_Model_Category $category */
?>

<?php foreach ($this->getCategoriesCollection() as $category){
    $productCollection = $this->getProductCollection($category);
    if (!$productCollection->count()) {
        continue;
    }?>


<a href="<?php echo $this->escapeHtml($category->getUrl())?>" class="hdr3"> <a class="fake-link title-vsm bold block" href="<?php echo $this->escapeHtml($category->getUrl()) ?>"><?php echo $category->getName() ?></a>
    <div class="cols-4">

        <?php foreach ($productCollection as $product){ ?>
            <div class="cols-4__item">
                <a href="<?php echo $product->getProductUrl() ?>" class="promo-product promo-product_adaptive-slider promo-product_full-w">
                    <?php if($product->getData('recommended_price_old')) {?><div class="discount-flag">скидка</div><?php }?>
                    <?php if($product->getData('archive')) {?><div class="archive-flag">Архивный товар</div><?php }?>
                    <div class="promo-product__image-w">
                        <img class="promo-product__image" src="<?php
                        echo $this->helper('catalog/image')->init($product, 'small_image')->resize(210)->setQuality(100); ?>" alt="<?php
                        echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"
                             alt=""/>
                    </div>
                    <div class="promo-product__title-w promo-product__title-w_hidden-1-col">
                        <div class="promo-product__title"><?php echo $this->escapeHtml($product->getName()) ?></div>
                    </div>
                    <div class="promo-product__price">
                        <div class="promo-product__price__price"><?php echo number_format($product->getData('recommended_price'), 2, ',', ' ');?>&nbsp;руб.</div>
                    </div>
                    <div class="promo-product__additional">при тираже&nbsp;<?php echo number_format($product->getData('recommended_count'), 0, ',', ' ') ?>&nbsp;шт.</div>
                    <div class="promo-product__sku"><?php echo $product->getSku() ?></div>
                </a>
            </div>
        <?php } ?>
    </div>

    <!-- <a href="<?php /*echo $category->getUrl() */?>"><?php /*echo $this
                    ->escapeHtml($category->getData('more_label') ? :"Посмотреть все ".$category->getName()." >>>")*/?></a>-->
<?php } ?>