<?php
/** @var Mage_Catalog_Block_Category_View $this */
/** @var Mage_Catalog_Helper_Output $_helper */
$_helper = $this->helper('catalog/output');
$_category = $this->getCurrentCategory();
$_imgHtml = '';
if ($_imgUrl = $_category->getImageUrl()) {
    $_imgHtml = '<p class="category-image"><img src="' . $_imgUrl . '" alt="' . $this->escapeHtml($_category->getName()) . '" title="' . $this->escapeHtml($_category->getName()) . '" /></p>';
    $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
}
?>
    <h1 class="title_mr-b title_mr-b_print-mr-r"><?php
    if(trim($_category->getData('navigation_label'))==""){
        echo($_category->getName());
    } else {
        echo($_category->getData('navigation_label'));
    }
    ?></h1>
<?php if ($_description = $this->getCurrentCategory()->getDescription()): ?>
    <div class="nanes">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
<?php endif; ?>

<?php if ($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif ($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>
<?php
else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>