<?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */

$catalogSearchHelper = $this->helper('catalogsearch');

?>

<?php ?>
<form id="search_footer_form" class="search search_ml-r search_mb search_footer-response" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="search__inner">
        <button type="submit" id="send_search_d" class="search__inner__button search__inner__button_gray">
            <span class="search__inner__button__icon"></span>
        </button>
        <input type="text" id="search_d" class="search__inner__text" name="q" placeholder="Поиск" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength() ?>"/>
        <div id="search_footer_autocomplete" class="search-autocomplete"></div>
    </div>
    <!--<script type="text/javascript">
        var searchForm = new Varien.searhForm('search_footer_form','search','<?php /*echo $this->__('Search entire store here...')*/?>');
        searchForm.initAutocomplete('<?php /*echo $catalogSearchHelper->getSuggestUrl() */?>','search_footer_autocomplete');
        </script>-->
    <script>
        jQuery('#send_search').on('click',function(event){
            event.preventDefault();
            if(jQuery('#search').val() == ''){
                event.preventDefault();
            } else {
                jQuery('#search_footer_form').submit();
            }
        });

        jQuery('#send_search_d').on('click',function(event){
            console.log('test');
            event.preventDefault();
            if(jQuery('#search_d').val() == ''){
                event.preventDefault();
            } else {
                jQuery('#search_footer_form').submit();
            }
        });

        </script>
</form>