
<h2 class="title-sm title_mr-b">Популярные сувениры</h2>

<div class="adaptive-slider js-adaptive-slider-fsize">
    <div class="adaptive-slider__pages-info">
        <span class="adaptive-slider__pages-info__pages"></span>
        <span class="delimeter"></span>
        <a href="#" class="adaptive-slider__pages-info__tobegin dotted">В начало</a>
    </div>
    <!--<ul class="adaptive-slider__inner"></ul>-->
    <!-- сюда вставляются слайды из заготовки <div class="adaptive-slider__content"></div> -->

    <div class="adaptive-slider__premade">
        <a href="#" class="promo-product promo-product_adaptive-slider promo-product1">
            <div class="promo-product__image-w">
                <img class="promo-product__image" src="images/content/adaptive-slider-product-demo1.png"
                     alt=""/>
            </div>
            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                <div class="promo-product__title">Зонт-трость механический &laquo;Радуга&raquo;</div>
            </div>
            <div class="promo-product__price">
                <div class="promo-product__price__price">413.48 <span class="rouble">a</span></div>
            </div>
            <div class="promo-product__additional">при тираже&nbsp;10 000 шт.</div>
        </a>

        <a href="#" class="promo-product promo-product_adaptive-slider promo-product2">
            <div class="promo-product__image-w">
                <img class="promo-product__image" src="images/content/adaptive-slider-product-demo2.png"
                     alt=""/>
            </div>
            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                <div class="promo-product__title">Зажигалка для барбекю</div>
            </div>
            <div class="promo-product__price">
                <div class="promo-product__price__price">204.75 <span class="rouble">a</span></div>
            </div>
            <div class="promo-product__additional">при тираже&nbsp;1 000 шт.</div>
        </a>

        <a href="#" class="promo-product promo-product_adaptive-slider promo-product3">
            <div class="promo-product__image-w">
                <img class="promo-product__image" src="images/content/adaptive-slider-product-demo3.png"
                     alt=""/>
            </div>
            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                <div class="promo-product__title">Набор для пикника на 4 персоны</div>
            </div>
            <div class="promo-product__price">
                от
                <div class="promo-product__price__price">1 897.28 <span class="rouble">a</span></div>
            </div>
            <div class="promo-product__additional">при тираже&nbsp;10 000 шт.</div>
        </a>

        <a href="#" class="promo-product promo-product_adaptive-slider promo-product4">
            <div class="promo-product__image-w">
                <img class="promo-product__image" src="images/content/adaptive-slider-product-demo4.png"
                     alt=""/>
            </div>
            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                <div class="promo-product__title">Зажигалка для барбекю</div>
            </div>
            <div class="promo-product__price">
                от
                <div class="promo-product__price__price">204.75 <span class="rouble">a</span></div>
            </div>
            <div class="promo-product__additional">при тираже&nbsp;10 000 шт.</div>
        </a>

        <a href="#" class="promo-product promo-product_adaptive-slider promo-product5">
            <div class="promo-product__image-w">
                <img class="promo-product__image" src="images/content/adaptive-slider-product-demo1.png"
                     alt=""/>
            </div>
            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                <div class="promo-product__title">Зонт-трость механический &laquo;Радуга&raquo;</div>
            </div>
            <div class="promo-product__price">
                <div class="promo-product__price__price">413.48 <span class="rouble">a</span></div>
            </div>
            <div class="promo-product__additional">при тираже&nbsp;10 000 шт.</div>
        </a>

        <a href="#" class="promo-product promo-product_adaptive-slider promo-product6">
            <div class="promo-product__image-w">
                <img class="promo-product__image" src="images/content/adaptive-slider-product-demo2.png"
                     alt=""/>
            </div>
            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                <div class="promo-product__title">Набор для пикника на 4 персоны</div>
            </div>
            <div class="promo-product__price">
                <div class="promo-product__price__price">1 897.28 <span class="rouble">a</span></div>
            </div>
            <div class="promo-product__additional">при тираже&nbsp;10 000 шт.</div>
        </a>

        <a href="#" class="promo-product promo-product_adaptive-slider promo-product5">
            <div class="promo-product__image-w">
                <img class="promo-product__image" src="images/content/adaptive-slider-product-demo3.png"
                     alt=""/>
            </div>
            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                <div class="promo-product__title">Зонт-трость механический &laquo;Радуга&raquo;</div>
            </div>
            <div class="promo-product__price">
                <div class="promo-product__price__price">413.48 <span class="rouble">a</span></div>
            </div>
            <div class="promo-product__additional">при тираже&nbsp;10 000 шт.</div>
        </a>

        <a href="#" class="promo-product promo-product_adaptive-slider promo-product6">
            <div class="promo-product__image-w">
                <img class="promo-product__image" src="images/content/adaptive-slider-product-demo4.png"
                     alt=""/>
            </div>
            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                <div class="promo-product__title">Набор для пикника на 4 персоны</div>
            </div>
            <div class="promo-product__price">
                <div class="promo-product__price__price">1 897.28 <span class="rouble">a</span></div>
            </div>
            <div class="promo-product__additional">при тираже&nbsp;10 000 шт.</div>
        </a>

        <a href="#" class="promo-product promo-product_adaptive-slider promo-product5">
            <div class="promo-product__image-w">
                <img class="promo-product__image" src="images/content/adaptive-slider-product-demo1.png"
                     alt=""/>
            </div>
            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                <div class="promo-product__title">Зонт-трость механический &laquo;Радуга&raquo;</div>
            </div>
            <div class="promo-product__price">
                <div class="promo-product__price__price">413.48 <span class="rouble">a</span></div>
            </div>
            <div class="promo-product__additional">при тираже&nbsp;10 000 шт.</div>
        </a>

    </div>
</div>
