<div class="user-helper__box__right">
    <div class="nav-n nav-n_simple js-nav-n">
        <ul class="nav-n__list">
            <li class="nav-n__list__item">
                <a class="nav-n__list__item__link nav-n__list__item__link_simple nav-n__list__item__link_arrow" href="http://novex.zaharov.local.barnaul.u-kit.ru/kosmetika-i-gigiena.html">
                    Посмотреть все
                </a>

                <div class="nav-n__inner-first-wrapper nav-n__inner-first-wrapper_right-alignment nav-n__inner-first-wrapper_right-alignment_1-2-set-default-pos">
                    <ul class="nav-n__inner-first">
                        <li class="nav-n__inner-first__item">
                            <a class="nav-n__inner-first__item__link" href="http://novex.zaharov.local.barnaul.u-kit.ru/kosmetika-i-gigiena/gigiena-polosti-rta.html">
                                Визитницы
                            </a>
                        </li>
                        <li class="nav-n__inner-first__item">
                            <a class="nav-n__inner-first__item__link" href="http://novex.zaharov.local.barnaul.u-kit.ru/kosmetika-i-gigiena/gigiena-polosti-rta.html">
                                Антистрессы
                            </a>
                        </li>
                        <li class="nav-n__inner-first__item">
                            <a class="nav-n__inner-first__item__link" href="http://novex.zaharov.local.barnaul.u-kit.ru/kosmetika-i-gigiena/gigiena-polosti-rta.html">
                                Монетницы
                            </a>
                        </li>
                        <li class="nav-n__inner-first__item">
                            <a class="nav-n__inner-first__item__link" href="http://novex.zaharov.local.barnaul.u-kit.ru/kosmetika-i-gigiena/gigiena-polosti-rta.html">
                                Мыло
                            </a>
                        </li>
                        <li class="nav-n__inner-first__item">
                            <a class="nav-n__inner-first__item__link" href="http://novex.zaharov.local.barnaul.u-kit.ru/kosmetika-i-gigiena/gigiena-polosti-rta.html">
                                Значки
                            </a>
                        </li>
                        <li class="nav-n__inner-first__item">
                            <a class="nav-n__inner-first__item__link" href="http://novex.zaharov.local.barnaul.u-kit.ru/kosmetika-i-gigiena/gigiena-polosti-rta.html">
                                Магниты
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

        </ul>
    </div>
</div>