<!--<div id="nav">

</div>


<div id="footer">
    <p class="copyright">+7 (495) 739–90–80<br>
        8–800 700–94–04, пн-пт, с 9:00 до 19:00 по московскому времени<br>
        e-mail:&nbsp;<a href="mailto:info@adverti.ru" style="font-size: 1em;">info@adverti.ru</a><br>
        <br>
        © 2003–2014 «Адверти» – <a href="<?php /*echo Mage::getBaseURL();*/?>" style="font-size: 1em;">сувенирная продукция</a></p>

    <div class="banner">
        <noindex>
            <?php /*echo $this->getChildHtml('counters') */?>
        </noindex>-->
        <?php /*?>
    <noindex>
            <!-- Yandex.Metrika informer -->
            <a href="http://metrika.yandex.ru/stat/?id=6853483&amp;from=informer"
               target="_blank" rel="nofollow"><img
                    src="//bs.yandex.ru/informer/6853483/3_0_EFEFEFFF_EFEFEFFF_0_pageviews"
                    style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика"
                    title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)"/></a>
            <!-- /Yandex.Metrika informer -->
            &nbsp;

            <!--LiveInternet logo--><a href="http://www.liveinternet.ru/click" target="_blank" rel="nofollow"><img
                    src="http://counter.yadro.ru/logo?15.2" border="0" width="88" height="31" alt=""
                    title="LiveInternet: показано число просмотров за 24 часа, посетителей за 24 часа и за сегодня"/></a><!--/LiveInternet-->
            &nbsp;

            <!-- HotLog -->
            <script type="text/javascript" language="javascript">
                hotlog_js = "1.0";
                hotlog_r = "" + Math.random() + "&s=137757&im=720&r=" +
                    escape(document.referrer) + "&pg=" + escape(window.location.href);
            </script>
            <script type="text/javascript" language="javascript1.1">
                hotlog_js = "1.1";
                hotlog_r += "&j=" + (navigator.javaEnabled() ? "Y" : "N");
            </script>
            <script type="text/javascript" language="javascript1.2">
                hotlog_js = "1.2";
                hotlog_r += "&wh=" + screen.width + "x" + screen.height + "&px=" +
                    (((navigator.appName.substring(0, 3) == "Mic")) ? screen.colorDepth : screen.pixelDepth);
            </script>
            <script type="text/javascript" language="javascript1.3">
                hotlog_js = "1.3";
            </script>
            <script type="text/javascript" language="javascript">
                hotlog_r += "&js=" + hotlog_js;
                document.write('<a href="http://click.hotlog.ru/?137757" target="_blank"><img ' +
                    'src="http://hit6.hotlog.ru/cgi-bin/hotlog/count?' +
                    hotlog_r + '" border="0" width="88" height="31" alt="HotLog"><\/a>');
            </script>
            <noscript>
                <a href="http://click.hotlog.ru/?137757" target="_blank" rel="nofollow"><img
                        src="http://hit6.hotlog.ru/cgi-bin/hotlog/count?s=137757&im=720" border="0"
                        width="88" height="31" alt="HotLog"></a>
            </noscript>
            <!-- /HotLog -->

            &nbsp;
            <script id="top100Counter" type="text/javascript"
                    src="http://counter.rambler.ru/top100.jcn?504461"></script>
            <noscript>
                <a href="http://top100.rambler.ru/navi/504461/">
                    <img src="http://counter.rambler.ru/top100.cnt?504461" alt="Rambler's Top100" border="0"/>
                </a>
            </noscript>

        </noindex>
 <?php */
        ?>
    </div>
</div>

<?php  //echo $this->getChildHtml('footerSearch')?>

<footer class="footer print-hide">
    <div class="footer__inner container clearfix">
        <div class="footer__right">
            <div class="short-nav">
                <div class="short-nav__item">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_block_drawing_logo')->toHtml() ?>
                </div>
                <div class="short-nav__item">
                   <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_block_preparation_layout')->toHtml() ?>
                </div>
                <div class="short-nav__item">
                   <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_block_help_on_site')->toHtml() ?>
                </div>
                <div class="short-nav__item">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_block_adverti')->toHtml() ?>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footerSearch') ?>
        <div class="footer__left">
            <div class="contacts">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_block_contacts')->toHtml() ?>
            </div>
            <div class="copyright">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_block_copyright')->toHtml() ?>
            </div>
        </div>
    </div>
</footer>

<form class="subscribe print-hide js-subscribe subscribe_hidden"  id="subscribe" method="post" action="http://cp.unisender.com/ru/subscribe?hash=5t6hdww5ancb8e7ddusan1gme7cpeqzsgfrt91jy">
    <input type="hidden" name="charset" value="UTF-8">
    <input type="hidden" name="default_list_id" value="2037427">
    <input type="hidden" name="overwrite" value="2">
    <input type="hidden" name="is_v5" value="1">
    <div class="subscribe__inner container">
        <a class="subscribe__closer" href="#">Убрать</a>
        <div class="subscribe__envelope"></div>
        <div class="subscribe__container-w">
            <div class="subscribe__container">
                <div class="subscribe__container__left">
                    <div class="subscribe__text">
                        Мы рассылаем скидки. Раз в месяц. Каждый месяц.
                    </div>
                </div>
                <div class="subscribe__container__right">
                    <!--[if IE 8]><span style="color:#fff;">Ваш e-mail:</span><style>.subscribe__input-w{width:25%;}.subscribe__container__left{width:150px;}</style><![endif]-->
                    <!--[if IE 9]><span style="color:#fff;">Ваш e-mail:</span><style>.subscribe__input-w{width:25%;}.subscribe__container__left{width:150px;}</style><![endif]-->
                    <div class="subscribe__input-w">
                        <input class="subscribe__input" name="email" id="email" type="text" placeholder="Ваш e-mail" />
                    </div>
                    <a class="button button_va-m button_orange" href="#" id="sub">Подписаться</a>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    jQuery('#sub').on('click',function(e){
        e.preventDefault();
        if(jQuery('#email').val() == ''){
            e.preventDefault();
        } else {
            jQuery('#subscribe').submit();
        }
    });
    jQuery(document).ready(function(){
        var showSubscribe = Mage.Cookies.get('showSubscribe');
        var subscribeForm = jQuery('.js-subscribe');
        if (showSubscribe != 'off') {
            subscribeForm.removeClass('subscribe_hidden');
        }
    });
</script>