<div class="header">
    <div class="logo" align=center>
        <a href="/">
            <?php echo $this->getChildHtml('logo') ?>
        </a>
        <?php echo $this->getChildHtml('counters') ?>
    </div>
    <div id="removeprint3" class="rightheader">
        <div class="orangemenu">
            <div class="twobg">
                <?php echo $this->getChildHtml('head_menu') ?>


            </div>
        </div>
        <div class="underthemenu2">
            <div class="phone">
                <?php echo $this->getChildHtml("phones") ?>
            </div>
            <div class="form">
                <div class="formpad">
                   <?php  echo $this->GetChildHtml('topSearch')?>
                </div>
            </div>
        </div>
    </div>
</div>